[cfg.services.core.redis.depot]
start = "--permanent-peer --peer 10.99.101.246:9000"

[cfg.services.core.hab-depot.depot]
start = "--permanent-peer --bind database:redis.depot,router:hab-depot.depot --peer 10.99.101.246:9000"
